### ISSUE TITLE
how to use the lib in tomcat ?

### ISSUE THREAD

**Issue by renyaoxiang** [damiencarol/jsr203-hadoop#29]
we want to use the jsr203 lib in tomcat, but found it unuseable , the classes of the lib can not be loaded by the jvm classloader. while we use the schema like hdfs://somefile, it was be handled by the default FileSystem class. how to fix the problem?

**Comment by damiencarol** [comment]
What is the pb? Could you provide a stack trace? How did you package it?
You need to have some Hadoop jar in the path (Hadoop jars are not included)

**Comment by renyaoxiang** [comment]
i want to make sure if is it a valid usage of using the lib in tomcat ? 
it makes no error and has no effect

**Comment by renyaoxiang** [comment]
@damiencarol 
Thank you!
