### ISSUE TITLE
Can I use the class Paths.java in the jsr203?

### ISSUE THREAD

**Issue by renyaoxiang** [damiencarol/jsr203-hadoop#30]
I have found the code in the Paths.java(java8 Paths)

    public static Path get(String first, String... more) {
        return FileSystems.getDefault().getPath(first, more); 
    }

Because the default FileSystem is not HdfsFileSystem, I think the Paths may not be used with jsr203 .
Is not it?

**Comment by damiencarol** [comment]
@renyaoxiang what you're showing is the default implementation.
If you use Paths.get(...), Java doesn't know any context. So it use the default implementation.
It is a normal behaviour.

**Comment by renyaoxiang** [comment]
Get it， thank you。
